apiVersion: v1
kind: Pod
metadata:
  name: multi-container-playground
spec:
  containers:
  - name: c1
    image: nginx:1.17.6-alpine
    volumeMounts:
    - mountPath: /kylych-vol
      name: kylych-storage
      
    env:
    - name: MY_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
  - name: c2
    image: busybox:1.31.1
    volumeMounts:
    - mountPath: /kylych-vol
      name: kylych-storage
    command: ["sh", "-c", "while true; do date >> /kylych-vol/date.log; sleep 1; done"]

  - name: c3
    image: busybox:1.31.1
    volumeMounts:
    - mountPath: /kylych-vol
      name: kylych-storage
    command: ["tail","-F", "/kylych-vol/date.log"]

  volumes:
  - name: kylych-storage
    emptyDir: {}