apiVersion: v1
kind: Pod
metadata:
  name: ready-if-service-ready
  labels:
    id: cross-server-ready
spec:
  containers:
  - name: nginx
    image: nginx:1.16.1
    ports:
    - containerPort: 80
    livenessProbe: 
      exec:
        command: ["true"]
      initialDelaySeconds: 5
      periodSeconds: 10
    command: ["/bin/sh"]
    args: ["-c", "apt update && apt install wget -y && nginx -g 'daemon off;'"]
    readinessProbe:
      exec:
        command: 
          - wget
          - -T2
          - -O-
          - http://service-am-i-ready:80
      initialDelaySeconds: 5
      periodSeconds: 5
---
apiVersion: v1
kind: Pod
metadata:
  name: am-i-ready
  labels:
    id: cross-server-ready
spec:
  containers:
  - name: nginx
    image: nginx:1.16.1-alpine
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-am-i-ready
spec:
  selector:
    id: cross-server-ready
  ports:
  - name: nginx
    port: 80