apiVersion: apps/v1
kind: Deployment
metadata:
  name: safari
  namespace: project-tiger
spec:
  replicas: 1
  selector:
    matchLabels:
      id: cross-server-ready
  template:
    metadata:
      labels:
        id: cross-server-ready
    spec:
      containers:
      - name: httpd
        image: httpd:2.4.41-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/tmp/safari-data"
          name: mypd
      volumes:
        - name: mypd
          persistentVolumeClaim:
            claimName: safari-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: safari-pv
  namespace: project-tiger
spec:
  storageClassName: ""
  capacity:
    storage: 2Gi
  accessModes: 
    - ReadWriteOnce
  hostPath:
    path: /home/Volumes/Data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: safari-pvc
  namespace: project-tiger
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi